application: asktheuniverseaquestion
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /img
  static_dir: public/img

- url: /css
  static_dir: public/css

- url: /js
  static_dir: public/js

- url: /_ah/spi/.*
  script: asktheuniverse.endpoint.app

- url: .*
  script: asktheuniverse.main.app

libraries:
- name: webapp2
  version: latest
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
- name: jinja2
  version: latest

admin_console:
  pages:
  - name: All Questions
    url: /listing
